#!/bin/sh
set -e

# Append the current value of RAILS_ENV to /etc/apache2/envvars
# on startup, if missing. Allows setting this value dynamically.
if ! grep -q 'RAILS_ENV' /etc/apache2/envvars ; then
    echo "
export RAILS_ENV=$RAILS_ENV" | tee -a /etc/apache2/envvars
fi

# Append custom APACHE_ENV_VARS
if [ "$APACHE_ENV_VARS" != "" ] ; then
    echo "
export $APACHE_ENV_VARS" | tee -a /etc/apache2/envvars
fi

# Run any custom startup scripts in /etc/on-server-start
if [ -d /etc/on-server-start ] ; then
    for script in /etc/on-server-start/*.sh; do
        exec $script
    done
fi

exec apache2ctl -e info -DFOREGROUND
